/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	event?: {
		timezone: string;
		name?: string;
		donationUrl?: string;
		[k: string]: unknown;
	};
	oengus?: {
		useSandbox?: boolean;
		[k: string]: unknown;
	};
	tracker?: {
		address?: string;
		socketAddress?: string;
		username?: string;
		password?: string;
		eventId?: number;
		[k: string]: unknown;
	};
	twitch?: {
		clientId?: string;
		clientSecret?: string;
		redirectUri?: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
