/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MixerState {
	connectionState: 'NOT_CONNECTED' | 'CONNECTING' | 'CONNECTED';
	channelNames: (string | null)[];
	auxInNames: (string | null)[];
	fxReturnNames: (string | null)[];
	busNames: (string | null)[];
	matrixNames: (string | null)[];
	dcaNames: (string | null)[];
	mainLRName: string | null;
	mainMonoName: string | null;
}
